---
title: "#3 Why Learn Programming"
author: "#IX - Hervy Qurrotul Ainur Rozi"
format: "revealjs"
logo: logo.svg
footer: |
    © 2023
    <a href="https://hervyqa.id" target="_blank">Hervy Qurrotul A.</a>
---

## Tujuan belajar {.smaller}

Topik: **Mengapa Belajar Pemrograman**

1. Murid mampu mengetahui manfaat dari pemrograman atau koding.
1. Murid mampu mengetahui jenis-jenis bahasa pemrograman.

## Manfaat belajar {.smaller}

1. Menambah wawasan tentang pentingnya pemrograman atau koding.
2. Menambah wawasan karir di masa depan.


# Apa sih **pemrograman** itu? {.smaller}

## Pemrograman {.smaller}

Pemrograman (program) adalah ilmu yang mempelajari _code_ (koding) mulai dari menulis, mengubah dan memperbaiki kode yang digunakan.

Apa sih kegunaan dari code itu? Code adalah salah satu dasar yang digunakan jika anda ingin membuat program operasi ataupun program komputer, karena awal dibuatnya semua program dibuat menggunakan kode maka untuk bisa menciptakan hal yang sama anda juga harus ikut menggunakan kode.

## Pemrograman {.smaller}

Code yang digunakan ini dibuat untuk pepmrogram agar sistem bisa melakukan pekerjaan sesuai dengan apa yang programer inginkan.

Tentunya pemrograman membutuhkan penyusunan kode yang sitemik dan tidak asal memasukkan kode saja.

Penginputan kode ini harus memperhatikan alogaritma dan bahasa pemrograman yang tidak mudah namun butuh penghitungan yang jeli. Oleh karena itu kenapa tidak semua orang bisa memiliki kemampuan ini karena skill yang dibutuhkan untuk mempelajari ini juga cukup sulit.

# Alasan harus belajar pemrograman dari sekarang?

## Sebagai persiapan {.smaller}

Belajar coding mulai dari sekarang bisa memberikan pemahaman tentang ilmu pemrograman jauh-jauh hari sebelum masuk universitas.

Sehingga saat sudah kuliah, atau ketika anda membutuhkan ilmu pemrograman komputer dalam pekerjaan, sudah selangkah lebih tahu.

Hal ini tentu membawa keuntungan daripada seseorang yang belum mempelajari coding sama sekali.

Setidaknya sudah punya dasar-dasarnya lebih dulu.

## Kesempatan karier {.smaller}

Belajar coding sangat penting di era digital seperti saat ini.

Meski tidak kuliah di bidang IT, tapi kalau punya kemampuan coding yang memadai, membuka peluang untuk mendapatkan pekerjaan yang berhubungan dengan ilmu tersebut.

Mulai dari Programmer, Web Engineer, Software Engineer, hingga Game Developer. Selain itu, ada juga bidang pekerjaan lain yang tidak terlalu fokus pada pemrograman, tapi tetap membutuhkan pemahaman dasar-dasar coding, seperti IT Analyst, Technical Writer dan Quality Assurance.

## Tingkatkan kemampuan _critical thinking_ dan _problem solving_ {.smaller}

Belajar pemrograman komputer atau coding, akan berhadapan dengan permasalahan yang memaksa berpikir kritis agar menemukan solusi. Ini dikenal dengan _critical thinking_ dan _problem solving_. Contohnya, saat sedang membuat sebuah program, lalu tiba-tiba ada error atau bug yang anda tidak tahu bagaimana cara mengatasinya. Tentu, anda akan terus berusaha mencari cara agar program yang anda buat bisa berjalan lancar.

Dengan begitu, kemampuan critical thinking dan problem solving anda akan makin terasah.

## Menambah pengalaman, relasi dan penghasilan {.smaller}

Belajar coding sejak dini juga bermanfaat ketika seseorang beranjak dewasa. Misalnya di masa kuliah, saat bisa menguasai coding, maka bisa mendapatkan tambahan uang saku dengan bekerja paruh waktu. Selain itu anda juga bisa mengikuti project di sekolah, kampus, baik bersama dosen atau teman.

## Hobi yang menyenangkan {.smaller}

Meski tujuan awal belajar coding hanya sebagai hobi, seseorang tetap boleh belajar suatu ilmu yang menurutmu menarik. anda bisa mempelajarinya sendiri melalui buku, artikel, atau video tutorial yang banyak tersebar di internet. Kursus privat juga bisa menjadi pilihan lainnya.

## Bermanfaat bagi orang lain {.smaller}

Belajar pemrograman bukan hanya bermanfaat bagi diri sendiri, tapi juga orang lain. Misalnya, anda berhasil membuat sebuah game edukasi, yang bisa membantu anak-anak belajar materi pelajaran dengan menyenangkan lewat permainan. 

## Melatih komunikasi {.smaller}

Belajar coding, ternyata tak hanya berdampak pada taraf hidup, melainkan juga melatih skill berkomunikasi dalam bersosialisasi.

Coding memberikan kesempatan bagi para programmer, untuk bertukar pikiran dan saling memberikan solusi seputar pemrograman.

Bahkan, para _programmer_ memiliki komunitas yang selalu aktif untuk memberikan referensi belajar dalam mengutarakan ide-ide kompleks.

## Menciptakan inovasi baru {.smaller}

Belajar coding, membuat para programmer dapat menciptakan berbagai teknologi yang memudahkan serta bermanfaat bagi masyarakat. Contoh saja aplikasi **Gojek**, yang saat ini menjadi salah satu start up besar di dunia yang telah memberikan sumbangsih dalam membangun perekonomian di Indonesia. Selain itu, banyak pula aplikasi baru yang bermunculan dan mengubah dunia.

# Any Question? {background-color="rgb(10, 132, 81)"}

# Medium Homework

1. Berhitung 1 sampai 5.

# Medium Homework {.smaller}

- Topik Kelompok:
    1. Kelompok 1: Bahasa pemrograman C dan C ++.
    1. Kelompok 2: Bahasa pemrograman Java dan Kotlin.
    1. Kelompok 3: Bahasa pemrograman HTML dan CSS.
    1. Kelompok 4: Bahasa pemrograman Dart dan Flutter.
    1. Kelompok 5: Bahasa pemrograman Python dan Numpy.
- Buatlah presentasi tentang bahasa pemrograman sesuai kelompok. Presentasi menjelaskan tentang deskripsi, sejarah, manfaat, tujuan, dan alasan mengapa harus belajar bahasa pemrograman tersebut.
- Pertemuan depan akan dipresentasikan setiap kelompok dengan PDF/PPT/ODP.

# What the Next?

Materi minggu depan apa ya...

* Topik: **Programming Language with Python**
* Deskripsi: _Belajar membuat program sederhana dengan bahasa python._
* Tempat: Laboratorium komputer.

[Back to home](/)
