---
title: "#5 Structure and Management of Company"
author: "#IX - Hervy Qurrotul Ainur Rozi"
format: "revealjs"
logo: logo.svg
footer: |
    © 2023
    <a href="https://hervyqa.id" target="_blank">Hervy Qurrotul A.</a>
---

## Learning objectives {.smaller}

Topik: **Keuntungan dari perangkat lunak terbuka**

1. Murid mampu mengetahui runtutan manajemen organisasi yang jelas dalam suatu perusahaan.
1. Murid mampu mengetahui perbedaan CEO, COO, CFO, CTO, dan CMO.
1. Murid mampu mengetahui tugas dan peranan CEO, COO, CFO, CTO, dan CMO.

# CEO, COO, CFO, CTO dan CMO? {background-color="rgb(10, 132, 81)"}

## Pengertian singkat {.smaller}

1. Kepanjangan CEO adalah Chief Executive Officer, CEO adalah pemegang kuasa tertinggi dalam perusahaan dan memiliki tanggung jawab untuk menetapkan suatu kebijakan berkaitan dengan keberlangsungan perusahaan.
1. Kepanjangan COO adalah Chief Operating Officer, COO adalah pimpinan yang memiliki tugas mengurus dan membuat kebijakan perusahaan pada bagian operasional, Chief Operating Officer (COO) sering juga disebut tangan kedua dari CEO.
1. Kepanjangan CFO adalah Chief Financial Officer, CFO adalah bagian dari pimpinan yang mengurus bagian keuangan perusahaan.
1. Kepanjangan CTO adalah Chief Technology Officer, tugas atau peran CTO adalah mengatur segala kegiatan yang berhubungan dengan teknologi dan informasi dalam perusahaan.
1. Kepanjangan CMO adalah Chief Marketing Officer, CMO adalah posisi eksekutif atau pimpinan perusahaan yang bertanggung jawab dalam urusan marketing atau pemasaran.

# CEO (Chief Executive Officer) {background-color="rgb(10, 132, 81)"}

# Pengertian CEO {.smaller}

* CEO adalah singkatan dari Chief Executive Officer. Sementara, arti CEO yakni pemegang kuasa tertinggi dalam perusahaan. Posisinya sebagai pemimpin, membuat Chief Executive Officer (CEO) memiliki tanggung jawab untuk menetapkan suatu kebijakan berkaitan dengan keberlangsungan perusahaan.
* CEO merupakan kunci dari suatu perusahaan. Dimana mereka harus mampu mengkomunikasikan arah dari perusahaan yang mereka pimpin kepada masyarakat ataupun pemerintah.  
* Selain tugasnya sebagai pemimpin, ada juga tugas–tugas lain yang harus CEO jalankan, terutama dalam hal kepemimpinan yang termanajemen dengan baik. Jika seorang CEO tidak memiliki kemampuan kepemimpinan, maka tugasnya tidak bisa dijalankan dengan baik.
* CEO adalah jantung dari perusahaan, sehingga mereka wajib tahu semua yang terjadi dalam perusahaan, semua itu bisa dilakukan dengan menerima laporan dari semua bagian kepala manajemen.

# COO (Chief Operating Officer) {background-color="rgb(10, 132, 81)"}

# Pengertian COO {.smaller}

* COO adalah singkatan dari Chief Operating Officer. Mereka adalah bagian dari pimpinan yang memiliki tugas membuat kebijakan perusahaan pada bagian operasional, Chief Operating Officer (COO) sering juga disebut tangan kedua dari CEO.
* COO sama juga posisinya dengan Executive Vice President. Sedangkan di Indonesia sendiri, CEO merupakan direktur utama dan dibantu COO yang bertindak sebagai direktur.
* COO adalah mengoperasikan secara internal dari perusahaan. Bahkan pada beberapa perusahaan, COO juga berperan aktif dalam menentukan quality control.
* CEO dan COO memiliki tugas yang saling melengkapi. Jika CEO fokus untuk memberi penjelasan kepada publik dan juga pemerintah, maka COO yang berperan aktif dalam mengendalikan internal dari perusahaan. Kebiasaan inilah yang membuat COO memiliki kemampuan teknis yang lebih.

# CFO (Chief Financial Officer) {background-color="rgb(10, 132, 81)"}

# Pengertian CFO {.smaller}

* CFO adalah singkatan dari Chief Financial Officer, CFO adalah bagian dari pimpinan yang mengurus bagian keuangan perusahaan. Berbagai macam tugas keuangan melekat pada kedudukan CFO, seperti; pencatatan, perencanaan keuangan, hingga pengadministrasian perusahaan.
* CFO memiliki tugas yang mirip dengan bendahara pada suatu organisasi. Sebagaimana fungsi utama Chief Financial Officer (CFO) yang mengatur kendali keuangan perusahaan, bahkan tidak jarang CFO juga menjalankan fungsi akuntansi.
* CFO memiliki tanggung jawab kepada CEO. Dimana mereka harus memberikan pertimbangan keputusan dalam hal keuangan perusahaan. Selain itu, CFO juga memiliki tanggung jawab dalam proses dealnya investasi oleh investor atau pinjaman dari pihak ketiga.
* Pada perusahaan yang bergerak dalam bidang keuangan, CFO merupakan pimpinan utama dalam perusahaan. Namun, berbeda pada perusahaan yang bergerak dalam bidang lain. Chief Financial Officer (CFO) menduduki jabatan ketiga dalam struktur perusahaan.

# CTO (Chief Technology Officer) {background-color="rgb(10, 132, 81)"}

# Pengertian CTO {.smaller}

* CTO adalah singkatan dari Chief Technology Officer, tugas atau peran CTO dalam perusahaan adalah mengatur segala kegiatan yang berhubungan dengan teknologi dan informasi dalam perusahaan.
* CTO ini banyak dimiliki perusahaan StartUp yang bergerak dalam bisnis internet ataupun aplikasi. Peran Chief Technology Officer (CTO) menjadi sangat penting dalam beberapa perusahaan.
* Posisi CTO saat ini juga diperlukan pada beberapa perusahaan berskala besar. Bahkan CTO saat ini sangat diperhitungkan dalam dunia perusahaan, untuk runtutan struktur organisasinya sendiri, CTO berada di bawah tanggung jawab CEO.

# CMO (Chief Marketing Officer) {background-color="rgb(10, 132, 81)"}

# Pengertian CMO {.smaller}

* CMO adalah singkatan dari Chief Marketing Officer. Jika melihat dari arti kata bahasanya, maka dapat disimpullkan bahwa fungsi dari CMO adalah dalam bidang marketing.
* CMO memiliki peran yang mirip dengan Direktur Marketing. Tetapi, ada juga yang menjelaskan bahwa CMO memiliki peran yang lebih luas dibanding Direktur Marketing.
* CMO biasanya berfokus pada pengawasan terhadap perencanaan, pengembangan, pelaksanaan, dan memberikan solusi kendala. Bahkan untuk tugas yang lebih luas, CMO juga memberikan forecast untuk persiapan pemasaran pada kesempatan berikutnya.

# Penutup {background-color="rgb(10, 132, 81)"}

# Kesimpulan {.smaller}

Tidak semua perusahaan memiliki posisi tersebut secara lengkap. Namun pada dasarnya, setiap perusahaan memiliki runtutan organisasi yang sama. Posisi–posisi yang telah dijelaskan di atas, biasa juga disebut dengan C-Levels. Istilah ini biasa digunakan pada perusahaan startup.

Sebelum mencapai karir pada tahapan C-Levels, tentu ada beberapa jenjang karir yang harus kamu lewati. Namun setidaknya, kamu perlu mengetahui pengertian dan perbedaan CEO, COO, CFO, CTO dan CMO agar bisa menjadi penyemangatmu dalam meraih karir.

# Any Question? {background-color="rgb(10, 132, 81)"}

# Simple Homework {.smaller}

1. Sebutkan 5 contoh tokoh CEO lokal (indonesia) dalam dunia perusahaan teknologi. Mulai dari nama dan riwayat perusahaannya secara singkat. Sebagai contoh: gojek, tokopedia, bukalapak, biznet, kaskus, dsb.
1. Sebutkan 5 contoh tokoh CEO luar negeri dalam dunia perusahaan teknologi. Mulai dari nama dan riwayat perusahaannya secara singkat. Sebagai contoh: google, facebook, pinterest, alibaba, ebay, dsb.

(setiap poin bernilai 10)

# What the Next?

Materi minggu depan apa ya...

* Topik: **Programming Language with Python (part 2)**
* Deskripsi: _Belajar membuat program sederhana konversi suhu dengan bahasa python (lanjutan)._
* Tempat: Laboratorium komputer.

[Back to home](/)
