---
title: "#3 Computer Science Jobs"
author: "#IX - Hervy Qurrotul Ainur Rozi"
format: "revealjs"
logo: logo.svg
footer: |
    © 2023
    <a href="https://hervyqa.id" target="_blank">Hervy Qurrotul A.</a>
---

## Tujuan belajar {.smaller}

Topik: **Pekerjaan dalam bidang Ilmuan Komputer**

1. Murid mampu mengetahui prospek dalam informatika.
1. Murid mampu mengetahui bahasa pemrograman.

## Manfaat belajar {.smaller}

1. Menambah wawasan pekerjaan dalam bidang informatika.
1. Menggali potensi diri dalam bidang pemrograman.

# Software engineer {.smaller}

Pekerjaan ini mengaplikasikan prinsip-prinsip pengelolaan dan optimalisasi software.

Hal itu seperti analisis teknik informatika dan matematika dalam desain, development, maintenance, hingga *testing software* komputer atau device lain.

Jenis-jenis software yang dibuat oleh seorang software engineer bermacam-macam, seperti sistem operasi dan *network distribution*, serta software untuk compiler yang mengonversi program untuk eksekusi pada komputer.

# IT consultant {.smaller}

IT consultant adalah salah satu peluang karier bagi lulusan teknik informatika. Profesi ini bertugas untuk menerapkan strategi teknologi informasi dalam perencanaan, pelaksanaan, hingga evaluasi di sebuah perusahaan.

Secara spesifik, IT consultant merupakan spesialis yang berfokus dalam proses integrasi teknologi informasi dalam bisnis.

Mereka diwajibkan untuk memberi saran pada klien terkait penggunaan teknologi informasi secara efisien untuk mencapai tujuan perusahaan.

Meskipun terkesan menarik, pekerjaan satu ini cukup menantang. Seorang IT consultant harus memiliki kemampuan analisis yang kuat untuk memahami masalah klien dan membuat solusi yang efektif.

# Web developer {.smaller}

Lulusan teknik informatika dapat bekerja sebagai web developer secara penuh waktu atau paruh waktu dalam beberapa jenis organisasi, termasuk korporasi dan pemerintah atau sebagai freelancer.

Pengetahuan yang harus diketahui oleh web developer antara lain adalah HMTL/XHMTL, CSS, JavaScript.

Selain itu, mereka juga harus menguasai server/client side architecture, programming dalam framework seperti Perl, Python, Ruby, PHP, Go, dan Java.

# Mobile application developer {.smaller}

Mobile application developer bertugas untuk membuat, menguji, dan memprogram aplikasi khusus untuk smartphine di berbagai sistem operasi seperti iOS, Android, dan Windows Phone.

Maka dari itu, pekerjaan satu ini juga memayungi profesi seperti android developer dan iOS developer.

Jika ingin menjadi mobile application developer, lulusan teknik informatika harus mempelajari bahasa pemrograman dan software development environment untuk platform yang mereka pilih.

Pasalnya, saat ini, banyak mobile platform yang memiliki bahasa intinya masing-masing, seperti Java untuk Android, Objective-C untuk iOS, dan C# untuk Windows Phone.

# Game developer {.smaller}

Game developer sendiri secara keseluruhan bekerja untuk mendesain dan membuat video game untuk komputer dan berbagai konsol, mulai dari konsep hingga eksekusi.

Adapun tugas-tugas yang dikerjakan oleh game developer meliputi:

* pembuatan storyline dan biografi karakter
* melaksanakan design review
* mendesain role-play mechanics
* membuat prototipe yang dibuat untuk staf dan manajemen perusahaan
* mendokumentasikan proses desain sebuah video game

Jika berkuliah di teknik informatika, sebaiknya menguasai bahasa-bahasa pemrograman utama seperti C++, Visual Basic, Java, dan MEL yang sering digunakan untuk keperluan game development.

# System analyst {.smaller}

System analyst sendiri merupakan seseorang yang menggunakan sistem khusus untuk mendesain solusi dalam arsitektur teknologi informasi.

Mereka diwajibkan untuk memodifikasi dan mengoptimalkan sistem yang ada sambil mengintegrasi fitur-fitur agar lebih efisien dan produktif.

Menurut Computer Science, system analyst akan terjun dalam proyek-proyek yang mengharuskannya untuk memeriksa model bisnis dan menganalisis kebutuhan sistem tersebut.

Setelah itu seorang system analyst melakukan pengembangan produk dan mengimplementasikan, mengatur, dan menguji solusinya dalam sistem.

# Data scientist {.smaller}

Mereka bertugas untuk mengubah data mentah menjadi informasi yang berharga menggunakan algoritma dan machine learning.

Data-data tersebut nantinya akan digunakan pihak manajemen untuk keperluan perencanaan strategi bisnis dan evaluasi ulang produk.

Dikarenakan tingkat demand-nya yang tinggi, data scientist dibutuhkan dalam berbagai sektor industri, seperti keuangan, pendidikan, riset ilmiah, ritel, teknologi informasi, dan e-commerce.

# Android developer {.smaller}

Sesuai namanya, Android developer bertugas untuk membuat dan merancang aplikasi agar dapat digunakan pada perangkat berbasis Android.

Maka dari itu, mereka harus menguasai sejumlah bahasa pemrograman yang relevan dengan keperluan Android, seperti Java dan Kotlin.

Nah, melihat kemajuan operating system tersebut, profesi satu ini sedang dibutuhkan oleh banyak perusahaan yang memiliki aplikasi.

# iOS developer {.smaller}

Profesi iOS developer juga menjadi prospek kerja yang menunggu mahasiswa teknik informatika setelah mereka nanti lulus.

Seperti Android developer, iOS developer bertugas untuk menciptakan aplikasi yang mampu untuk digunakan perangkat iOS.

Hasilnya, mereka harus memahami iOS environment dan menguasai bahasa pemrograman seperti Swift atau objective-C.

# Cyber security analyst {.smaller}

Jika orang awam bertanya jurusan teknik informatika kerja apa? Salah satu jawaban paling baik yang bisa diberikan adalah cyber security analyst.

Profesi satu ini sedang menjadi tren. Sebab, banyak aplikasi dan software baru yang memiliki masalah keamanan dalam sistemnya.

Cyber security analyst diperlukan untuk mengatasi masalah tersebut dengan sistem keamanan yang kebal dari data breach atau bug yang tak diinginkan.

# SEO specialist {.smaller}

Menurut Best College Reviews, profesi ini cocok untuk alumni teknik informatika yang gemar dengan dunia marketing dan penulisan.

Mereka bertugas untuk membuat website lebih ramah terhadap search engine supaya bisa ditemukan dengan mudah oleh para audiens.

Untuk keperluan sehari-hari, SEO specialist wajib menguasai tools seperti i Google Search Console, Google Analytics, MOZ, SEMRUSH, dan masih banyak lagi.

# Database administrator {.smaller}

Database administrator merupakan prospek kerja lainnya yang sering dipilih oleh lulusan teknik informatika.

Tugas mereka meliputi proses rancangan desain database, melakukan pemeliharaan, dan perbaikan suatu basis data.

Pekerjaan satu ini juga sedang menjadi tren di dunia kerja. Sebab, hampir setiap perusahaan pasti memiliki database untuk menyimpan data-data penting.

# Cloud architect {.smaller}

Hal ini berlaku karena penyimpanan data kini mulai beralih ke sistem cloud dan bukan lagi pada perangkat hardware.

Tugas dari cloud architect sendiri adalah mendesain aplikasi berbasis cloud, melakukan manajemen cloud, dan monitoring data yang tersimpan di dalamnya.

Selain itu, mereka juga harus mempunyai pengetahuan mengenai sistem operasi seperti Linux dan Windows serta menguasai jaringan TCP/IP, HTTP, hingga DNS.

# Software tester {.smaller}

Mereka yang memiliki pekerjaan ini berperan untuk menguji dan mengevaluasi kinerja software yang sudah diciptakan para developer.

Software tersebut akan diuji baik dari segi functional testing, unit testing, UI testing, dan masih banyak lagi.

# Network engineer {.smaller}

Pilihan karier ini akan selalu dibutuhkan. Sebab, infrastruktur jaringan sudah pasti diperlukan jika perusahaan ingin membangun platform komunikasi untuk para user.

Tugas dari seorang network engineer sendiri adalah merencanakan, merancang desain, mengelola, dan menyelesaikan semua permasalahan dalam jaringan.

# Full stack developer {.smaller}

Di sini, mereka berperan untuk mengembangkan sisi pekerjaan dalam aplikasi atau software, termasuk database, server, sistem engineering, maupun permintaan lainnya dari klien.

Untuk menjadi seorang full stack developer diharuskan menguasai konsep dari teknologi terkini. Karena akan bertugas untuk mengembangkan sisi front end dan back end.

# Front end developer {.smaller}

Mereka bertugas untuk mengelola bagian pemrograman yang dapat dilihat secara langsung oleh pengguna dalam aplikasi.

Untuk menjadi seorang front end developer, harus menguasai HTML, CSS, dan bahasa pemrograman JavaScript.

HTML sendiri digunakan sebagai kerangka dari suatu website. CSS biasanya dimanfaatkan untuk memperindah tampilan dalam situs. Sementara, JavaScript digunakan untuk memperkuat fungsi tiap elemen dalam website.

# Back end developer {.smaller}

Mereka sejatinya adalah para programmer yang bertugas untuk mengelola dan merancang sistem yang berada di belakang layar sistem aplikasi.

Untuk memiliki pekerjaan ini, ada banyak bahasa pemrograman yang harus dikuasai, seperti Java, PHP, Ruby, Python, JavaScript (Node.js).

Back end developer sendiri akan menangani keperluan data dari website seperti server dan database sambil merancang sistem serta API.

# Computer forensic investigator {.smaller}

Mereka secara khusus bekerja pada suatu perusahaan atau organisasi pemerintahana secara privat.

Computer forensic investigator juga dapat ditemukan bekerja di lembaga dan badan penegakan hukum, seperti kepolisian.

Tugas utama mereka adalah menemukan bukti legal atau pelanggaran hukum di dalam media penyimpanan atau perangkat hardware lainnya.

# Web administrator {.smaller}

Tugas mereka adalah menyediakan host web untuk organisasi, memberikan akses untuk pengguna tertentu, dan  membuat server email.

Pada perusahaan yang lebih besar, web administrator juga ditugaska untuk membantu pengguna memahami fungsi dasar sistem yang mereka gunakan.

# UX researcher {.smaller}

Di sini, mereka berperan untuk menjalankan riset dan menemukan solusi yang dapat memenuhi kebutuhan pelanggan dalam aplikasi.

Mereka juga perlu mencari bentuk dan fitur dalam produk yang relevan dengan kebutuhan di pasar.

# Web designer {.smaller}

Sesuai namanya, mereka berperan untuk merancang tampilan UI dan fitur-fitur di dalam sebuah situs web.

Meskipun terkesan simpel, mereka harus bisa menciptakan desain modern yang tampak ramah dan mudah untuk dimanfaatkan para pengguna.

# Applications engineer {.smaller}

Seorang applications engineer adalah penghubung antara para developer dan pelanggan. Mereka meninjau data penjualan dan membantu dalam produksi software yang kompleks.

Mereka juga mempresentasikan temuan para developer kepada publik dan menyaring feedback tentang perubahan yang perlu dilakukan dalam apikasi.

# Penetration tester {.smaller}

Mereka bertugas untuk melakukan pengujian resmi pada sistem komputer untuk mengungkap kelemahan keamanannya yang dapat dimanfaatkan oleh penjahat.

Plihan beberapa spesialisasi dalam pekerjaan ini, seperti:

* jaringan dan infrastruktur
* sistem operasi Windows, Linux, dan Mac
* embedded computer systems
* aplikasi web/seluler
* sistem kontrol SCADA (supervisory control and data acquisition)
* Internet of Things (IoT)

# Any Question? {background-color="rgb(10, 132, 81)"}

# Simple Homework {.smaller}

1. Pilih salah satu jenis pekerjaan dalam bidang informatika lalu jelaskan tugas dan tujuannya secara mendetail.
1. Dari pekerjaan yang dipilih sebelumnya di nomer 1, bahasa pemrograman apa yang harus dikuasai agar menjadi profesional dalam bidangnya?

# What the Next?

Materi minggu depan apa ya...

* Topik: **Why Learn Programming?**
* Deskripsi: _Mempelajari alasan belajar pemrograman komputer?._
* Tempat: Laboratorium komputer.

[Back to home](/)